name: Lint
on: pull_request

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: lts/*
      - name: Set up NPM credentials
        run: |
          printf -- "//npm.pkg.github.com/:_authToken=${{ env.TOWER_PACKAGE_TOKEN }}\n@tari-labs:registry=https://npm.pkg.github.com" > .npmrc
        env:
          TOWER_PACKAGE_TOKEN: ${{ secrets.TOWER_PACKAGE_TOKEN }}
      - name: Install Node.js dependencies
        run: npm ci
      - name: check lint/prettier errors
        run: npm run lint
      - name: check taplo
        run: npm run lint:taplo
